### ISSUE TITLE
Russian Localization - Access Permit

### ISSUE THREAD

**Issue by Longer** [dukope/BugsPlease#25]
Field "physical appearance" sometime not full
![2014-02-03_00001](https://f.cloud.github.com/assets/103578/2062092/b9a5933e-8c7b-11e3-918d-aa23e7488421.jpg)
![2014-02-03_00002](https://f.cloud.github.com/assets/103578/2062093/b9b0bdf4-8c7b-11e3-97ca-19d102393e04.jpg)

**Comment by dukope** [comment]
Damn! This is entirely my fault. I didn't set a width limit for this string in the localization tool. In fact, when asked about it I explicitly said "there is no limit" because I'd forgotten about this document. The other document where these appearance strings appear (the Identity Supplement) has plenty of space.

I'll update the localization tool with a width limit and ask the localizers to update their strings. Thanks for the report, @Longer.

**Comment by dukope** [comment]
After updating the tool, it looks like the only string here that overflows is this one:

> Волосы вьющиеся, прическа "каре"

I think it's safe to just remove the second part to make it fit, leaving:

> Волосы вьющиеся

Does that look ok? I'll also confirm with the Russian localizers.

**Comment by Longer** [comment]
It ok.

**Comment by dukope** [comment]
Fixed in 1.1.57
