### ISSUE TITLE
Linux Version problem (steam)

### ISSUE THREAD

**Issue by Longer** [dukope/BugsPlease#4]
After change on beta brunch, "Install" button still not active ("Papers, Please is not available on your current platform.").

**Comment by dukope** [comment]
What's your Steam id? (Email me at the helptest address if you don't want to post it here.)

**Comment by Longer** [comment]
Sent on email.

**Comment by dukope** [comment]
I'm asking Valve about this now. Will post here when I get an update.

**Comment by ghost** [comment]
I think I know what's the problem. The Linux depot is not currently included in all Steam packages. As it happens, it works for me as I own the right package (27591), but anyone who got it differently (i.e. not a press copy), will not be able to install it.

With this, you can limit the number of Linux players quite easily, if you're worried about the beta password being leaked. You could actually possibly go one step further, and set up separate depots for the whole update instead of just a beta branch, essentially limiting this to _only_ the users you selected on all three OSes.

**Comment by dukope** [comment]
Well that sounds exactly right. @flibitijibibo even warned me about this issue but for some reason I blanked on it.

I'd rather not set up separate depots since that adds complexity to my build process. And I'd have to go through Valve to set up a separate package anyways; that's a dependency I'd rather not have.

I (finally) found the place in Steamworks where I can add the Linux depot to the main public package. But will that break things with people not on the beta branch?

**Comment by ghost** [comment]
I don't see how it could. On Linux, those not on the beta branch should still just see the same thing - an empty download when they try to install it. And as I had it on Windows prior to this without any issues either, I can't imagine anything breaking there.

**Comment by dukope** [comment]
Ok, done! If you were stuck with an empty Linux download, try again. Thanks for the tip, soeb.

**Comment by Longer** [comment]
Thx, now work.
